### ISSUE TITLE
CSSがコンパイルされなくなりました。

### ISSUE THREAD

**Issue by seito2014** [frontainer/frontnote#5]
バージョン0.1.0から1.0.0に上げたところ、CSSがコンパイルされなくなりました。
再び0.1.0に戻すか、gulpのfrontnoteのタスク部分をコメントアウトしたらコンパイルできました。

ちなみに試したのはこちら↓のmasterに置いてあるテンプレです。
https://github.com/seito2014/template

**Comment by frontainer** [comment]
これはfrontnoteではなくgulp-frontnoteなのでリポジトリが異なります。
内容をgulp-frontnoteに移し、こちらはクローズします。
