### ISSUE TITLE
file overviewの記述が全てタイトル扱いになる

### ISSUE THREAD

**Issue by yama-t** [frontainer/frontnote#6]
CSSファイルにfile overviewを設定し、タイトルとコメントを書きましたが、
コメント部分もタイトル扱いになってしまいます。
また、タイトルの前にも改行が入ってしまいます。
# 環境

Windows7 Professional 32bit
# バージョン
- Node: 0.12.7 ※
- gulp-frontnote: 1.0.2
- frontnote: 1.1.1

※nodeのバージョンを4.4.1にアップデートしましたが、改善しませんでした。
# テンプレート
## index.ejs

``` html
<nav class="fn-sidebar">
    <a href="./index.html" class="fn-menu<%if(overview){%> fn-is-active<%}%>">Overview</a>
    <!-- 全ファイル -->
    <% files.forEach(function(file) { %>
    <!-- スタイルガイドへのリンク -->
    <a href="<%- file.url %>" class="fn-menu<%if(helpers.isCurrent(current,file)){%> fn-is-active<%}%>">
        <% if (file.overview) { %>
            <%- file.overview.title %>
        <% } else { %>
            <%- file.fileName %>
        <% } %>
    </a>
    <% }) %>
</nav>

<h2 class="fn-heading2">
    <% if (current.overview) { %>
    <%-current.overview.title%>
    <% } else { %>
    <%-current.fileName%>
    <% } %>
    <small class="fn-sub-heading"><%-current.file%></small>
</h2>
<% if (current.overview) { %>
<p class="fn-comment"><%-current.overview.comment%></p>
<% } %>
```
## color.css

``` css
/*
#overview
Color

コメント
*/
```
# ビルド結果

``` html
<nav class="fn-sidebar">
    <a href="./index.html" class="fn-menu">Overview</a>
    <!-- 全ファイル -->

    <!-- スタイルガイドへのリンク -->
    <a href="styleguide2-template-common-color.html" class="fn-menu fn-is-active">


        <br>Color
        <br>
        <br>コメント

    </a>

</nav>

<h2 class="fn-heading2">


    <br>Color
    <br>
    <br>コメント

    <small class="fn-sub-heading">/path/color.css</small>
</h2>
<p class="fn-comment"></p>
```

**Comment by frontainer** [comment]
頂いたソースには間違いはなさそうということがわかりました。
その後試した結果、改行コードの違いによって空行として認識されないことがわかりました。

改行コード
- LF = 正しく分割される
- CRLF = 分割されず `<br>` になる
- CR = 分割されず\nになる

おそらく環境がWindowsではないかと思いますが、不具合として引き続き調査します。
とりいそぎ改行コードを `LF` に変換すれば正しく動作するようになります。

**Comment by yama-t** [comment]
コメントありがとうございます。OSはWindows7です。issueの方にも追記しておきました。
改行コードの問題なのですね。
改行コードをCRLFからLFに変更すると、正しく動作することを確認しました。
よろしくお願いします。

**Comment by frontainer** [comment]
@yama-t 
https://github.com/frontainer/frontnote/commit/a538a70f1dabc41e65b85f387c74ff7f86a7ea01

今回の修正で改行コードが異なっても正しく出力されるようになりました。
gulp-frontnote1.0.3(frontnote1.1.2)であれば正しく動作すると思いますので、アップデートをお願いいたします。

`npm update gulp-frontnote --save-dev`

**Comment by yama-t** [comment]
アップデート後、CRLFの改行コードでも正しく動作することを確認しました。
対応頂きまして、ありがとうございます。

**Comment by frontainer** [comment]
確認ありがとうございます。では本件はクローズします！
